import { Building, Event } from '@/types';

// Chitkara University Rajpura, Punjab coordinates
export const CAMPUS_CENTER = {
  lat: 30.5156,
  lng: 76.6596,
};

export const INITIAL_MAP_REGION = {
  latitude: CAMPUS_CENTER.lat,
  longitude: CAMPUS_CENTER.lng,
  latitudeDelta: 0.008,
  longitudeDelta: 0.008,
};

export const BUILDINGS: Building[] = [
  {
    building_id: 'main_gate',
    name: 'Main Gate & Reception',
    short_name: 'Main Gate',
    description: 'The main entrance to Chitkara University Rajpura campus with security checkpoint, visitor passes, and information desk.',
    category: 'services',
    floor_count: 1,
    coordinates: { lat: 30.5135, lng: 76.6575 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: false,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Security', 'Visitor passes', 'Information desk'],
    operating_hours: {
      monday: { open: '06:00', close: '22:00', is_closed: false },
      tuesday: { open: '06:00', close: '22:00', is_closed: false },
      wednesday: { open: '06:00', close: '22:00', is_closed: false },
      thursday: { open: '06:00', close: '22:00', is_closed: false },
      friday: { open: '06:00', close: '22:00', is_closed: false },
      saturday: { open: '06:00', close: '22:00', is_closed: false },
      sunday: { open: '06:00', close: '22:00', is_closed: false },
    },
    marker_emoji: '🚪',
    marker_color: '#64748B',
  },
  {
    building_id: 'admin_block',
    name: 'Administrative Block',
    short_name: 'Admin Block',
    description: 'Central administrative building housing admissions, finance office, registrar office, and HR departments.',
    category: 'admin',
    floor_count: 4,
    coordinates: { lat: 30.5145, lng: 76.6585 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Admissions', 'Finance office', 'Principal office', 'HR'],
    operating_hours: {
      monday: { open: '09:00', close: '17:00', is_closed: false },
      tuesday: { open: '09:00', close: '17:00', is_closed: false },
      wednesday: { open: '09:00', close: '17:00', is_closed: false },
      thursday: { open: '09:00', close: '17:00', is_closed: false },
      friday: { open: '09:00', close: '17:00', is_closed: false },
      saturday: { open: '09:00', close: '13:00', is_closed: false },
      sunday: { open: '00:00', close: '00:00', is_closed: true },
    },
    marker_emoji: '🏛️',
    marker_color: '#1E40AF',
  },
  {
    building_id: 'library',
    name: 'Learning Resource Centre',
    short_name: 'LRC',
    description: 'The main library with extensive collection, digital resources, reading halls, and study spaces. Open from 9 AM to 9 PM.',
    category: 'library',
    floor_count: 3,
    coordinates: { lat: 30.5160, lng: 76.6595 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: true,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: true,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Book lending', 'Digital library', 'Study rooms', '24hr study hall (ground floor)'],
    operating_hours: {
      monday: { open: '08:00', close: '20:00', is_closed: false },
      tuesday: { open: '08:00', close: '20:00', is_closed: false },
      wednesday: { open: '08:00', close: '20:00', is_closed: false },
      thursday: { open: '08:00', close: '20:00', is_closed: false },
      friday: { open: '08:00', close: '20:00', is_closed: false },
      saturday: { open: '09:00', close: '18:00', is_closed: false },
      sunday: { open: '10:00', close: '14:00', is_closed: false },
    },
    marker_emoji: '📚',
    marker_color: '#7C3AED',
  },
  {
    building_id: 'cafeteria',
    name: 'Student Cafeteria',
    short_name: 'Cafeteria',
    description: 'The main dining facility serving breakfast, lunch, dinner, snacks, and beverages throughout the day.',
    category: 'food',
    floor_count: 2,
    coordinates: { lat: 30.5155, lng: 76.6610 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Breakfast', 'Lunch', 'Dinner', 'Snacks', 'Coffee'],
    operating_hours: {
      monday: { open: '07:00', close: '22:00', is_closed: false },
      tuesday: { open: '07:00', close: '22:00', is_closed: false },
      wednesday: { open: '07:00', close: '22:00', is_closed: false },
      thursday: { open: '07:00', close: '22:00', is_closed: false },
      friday: { open: '07:00', close: '22:00', is_closed: false },
      saturday: { open: '08:00', close: '21:00', is_closed: false },
      sunday: { open: '08:00', close: '20:00', is_closed: false },
    },
    marker_emoji: '🍽️',
    marker_color: '#D97706',
  },
  {
    building_id: 'cs_block',
    name: 'De-Morgan Block',
    short_name: 'De-Morgan',
    description: 'Computer Science and Engineering department with computer labs, AI/ML facilities, seminar halls, and faculty offices.',
    category: 'academic',
    floor_count: 4,
    coordinates: { lat: 30.5168, lng: 76.6592 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: true,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Computer labs', 'AI/ML lab', 'Seminar hall', 'Faculty offices'],
    operating_hours: {
      monday: { open: '08:00', close: '20:00', is_closed: false },
      tuesday: { open: '08:00', close: '20:00', is_closed: false },
      wednesday: { open: '08:00', close: '20:00', is_closed: false },
      thursday: { open: '08:00', close: '20:00', is_closed: false },
      friday: { open: '08:00', close: '18:00', is_closed: false },
      saturday: { open: '09:00', close: '14:00', is_closed: false },
      sunday: { open: '00:00', close: '00:00', is_closed: true },
    },
    marker_emoji: '💻',
    marker_color: '#0891B2',
  },
  {
    building_id: 'engineering_block',
    name: 'Engineering Block',
    short_name: 'Engineering',
    description: 'Engineering departments including Mechanical, Civil, and Electrical with workshops, labs, and project rooms.',
    category: 'academic',
    floor_count: 4,
    coordinates: { lat: 30.5172, lng: 76.6605 },
    accessibility: {
      wheelchair_accessible: false,
      has_elevator: false,
      has_ramp: false,
      has_accessible_restroom: false,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: false,
    },
    services: ['Workshop', 'CAD lab', 'Project rooms'],
    operating_hours: {
      monday: { open: '08:00', close: '18:00', is_closed: false },
      tuesday: { open: '08:00', close: '18:00', is_closed: false },
      wednesday: { open: '08:00', close: '18:00', is_closed: false },
      thursday: { open: '08:00', close: '18:00', is_closed: false },
      friday: { open: '08:00', close: '17:00', is_closed: false },
      saturday: { open: '09:00', close: '14:00', is_closed: false },
      sunday: { open: '00:00', close: '00:00', is_closed: true },
    },
    marker_emoji: '⚙️',
    marker_color: '#6B7280',
  },
  {
    building_id: 'medical_center',
    name: 'Health Center',
    short_name: 'Health Center',
    description: 'Campus medical facility with emergency care, general physician, pharmacy, and ambulance services.',
    category: 'medical',
    floor_count: 2,
    coordinates: { lat: 30.5142, lng: 76.6618 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Emergency care', 'General physician', 'Pharmacy', 'Ambulance'],
    operating_hours: {
      monday: { open: '00:00', close: '23:59', is_closed: false },
      tuesday: { open: '00:00', close: '23:59', is_closed: false },
      wednesday: { open: '00:00', close: '23:59', is_closed: false },
      thursday: { open: '00:00', close: '23:59', is_closed: false },
      friday: { open: '00:00', close: '23:59', is_closed: false },
      saturday: { open: '00:00', close: '23:59', is_closed: false },
      sunday: { open: '00:00', close: '23:59', is_closed: false },
    },
    marker_emoji: '🏥',
    marker_color: '#DC2626',
  },
  {
    building_id: 'auditorium',
    name: 'University Auditorium',
    short_name: 'Auditorium',
    description: 'The main auditorium for events, convocation ceremonies, cultural programs, and conferences with modern facilities.',
    category: 'academic',
    floor_count: 2,
    coordinates: { lat: 30.5165, lng: 76.6580 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: true,
      step_free_entrance: true,
    },
    services: ['Events', 'Convocation', 'Conferences', 'Wheelchair seating'],
    operating_hours: {
      monday: { open: '09:00', close: '18:00', is_closed: false },
      tuesday: { open: '09:00', close: '18:00', is_closed: false },
      wednesday: { open: '09:00', close: '18:00', is_closed: false },
      thursday: { open: '09:00', close: '18:00', is_closed: false },
      friday: { open: '09:00', close: '18:00', is_closed: false },
      saturday: { open: '09:00', close: '18:00', is_closed: false },
      sunday: { open: '00:00', close: '00:00', is_closed: true },
    },
    marker_emoji: '🎭',
    marker_color: '#9333EA',
  },
  {
    building_id: 'sports_complex',
    name: 'Sports Complex',
    short_name: 'Sports',
    description: 'Modern sports facility with gym, indoor courts for basketball and badminton, swimming pool, and outdoor grounds.',
    category: 'sports',
    floor_count: 3,
    coordinates: { lat: 30.5180, lng: 76.6570 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Gym', 'Basketball court', 'Swimming pool', 'Badminton', 'Cricket ground'],
    operating_hours: {
      monday: { open: '06:00', close: '21:00', is_closed: false },
      tuesday: { open: '06:00', close: '21:00', is_closed: false },
      wednesday: { open: '06:00', close: '21:00', is_closed: false },
      thursday: { open: '06:00', close: '21:00', is_closed: false },
      friday: { open: '06:00', close: '21:00', is_closed: false },
      saturday: { open: '06:00', close: '21:00', is_closed: false },
      sunday: { open: '06:00', close: '20:00', is_closed: false },
    },
    marker_emoji: '🏋️',
    marker_color: '#16A34A',
  },
  {
    building_id: 'boys_hostel',
    name: 'Boys Hostel',
    short_name: 'Boys Hostel',
    description: 'Student residence for male students with modern amenities, common rooms, Wi-Fi, and mess facilities.',
    category: 'hostel',
    floor_count: 6,
    coordinates: { lat: 30.5185, lng: 76.6595 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: true,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Student residence', 'Common room', 'Laundry', 'Accessible rooms available'],
    operating_hours: {
      monday: { open: '00:00', close: '23:59', is_closed: false },
      tuesday: { open: '00:00', close: '23:59', is_closed: false },
      wednesday: { open: '00:00', close: '23:59', is_closed: false },
      thursday: { open: '00:00', close: '23:59', is_closed: false },
      friday: { open: '00:00', close: '23:59', is_closed: false },
      saturday: { open: '00:00', close: '23:59', is_closed: false },
      sunday: { open: '00:00', close: '23:59', is_closed: false },
    },
    marker_emoji: '🏠',
    marker_color: '#0369A1',
  },
  {
    building_id: 'girls_hostel',
    name: 'Girls Hostel',
    short_name: 'Girls Hostel',
    description: 'Student residence for female students with modern amenities, common rooms, Wi-Fi, and mess facilities.',
    category: 'hostel',
    floor_count: 6,
    coordinates: { lat: 30.5188, lng: 76.6605 },
    accessibility: {
      wheelchair_accessible: false,
      has_elevator: false,
      has_ramp: false,
      has_accessible_restroom: false,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: false,
    },
    services: ['Student residence', 'Common room', 'Laundry'],
    operating_hours: {
      monday: { open: '00:00', close: '23:59', is_closed: false },
      tuesday: { open: '00:00', close: '23:59', is_closed: false },
      wednesday: { open: '00:00', close: '23:59', is_closed: false },
      thursday: { open: '00:00', close: '23:59', is_closed: false },
      friday: { open: '00:00', close: '23:59', is_closed: false },
      saturday: { open: '00:00', close: '23:59', is_closed: false },
      sunday: { open: '00:00', close: '23:59', is_closed: false },
    },
    marker_emoji: '🏠',
    marker_color: '#0369A1',
  },
  {
    building_id: 'parking_main',
    name: 'Main Parking Area',
    short_name: 'Parking',
    description: 'Main parking area near entrance with car parking, two-wheeler parking, and visitor parking zones.',
    category: 'parking',
    floor_count: 1,
    coordinates: { lat: 30.5138, lng: 76.6582 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: false,
      has_accessible_restroom: false,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Car parking', 'Bike parking', 'Accessible bays', 'EV charging'],
    operating_hours: {
      monday: { open: '00:00', close: '23:59', is_closed: false },
      tuesday: { open: '00:00', close: '23:59', is_closed: false },
      wednesday: { open: '00:00', close: '23:59', is_closed: false },
      thursday: { open: '00:00', close: '23:59', is_closed: false },
      friday: { open: '00:00', close: '23:59', is_closed: false },
      saturday: { open: '00:00', close: '23:59', is_closed: false },
      sunday: { open: '00:00', close: '23:59', is_closed: false },
    },
    marker_emoji: '🅿️',
    marker_color: '#374151',
  },
  {
    building_id: 'innovation_hub',
    name: 'Innovation & Incubation Center',
    short_name: 'Innovation Hub',
    description: 'Research labs, startup incubation center, innovation facilities, and entrepreneurship development cell.',
    category: 'lab',
    floor_count: 3,
    coordinates: { lat: 30.5170, lng: 76.6615 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: true,
      has_ramp: true,
      has_accessible_restroom: true,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Research labs', 'Startup incubator', '3D printing', 'Floors 4-5 restricted access'],
    operating_hours: {
      monday: { open: '08:00', close: '20:00', is_closed: false },
      tuesday: { open: '08:00', close: '20:00', is_closed: false },
      wednesday: { open: '08:00', close: '20:00', is_closed: false },
      thursday: { open: '08:00', close: '20:00', is_closed: false },
      friday: { open: '08:00', close: '18:00', is_closed: false },
      saturday: { open: '09:00', close: '14:00', is_closed: false },
      sunday: { open: '00:00', close: '00:00', is_closed: true },
    },
    marker_emoji: '🔬',
    marker_color: '#0891B2',
  },
  {
    building_id: 'food_court',
    name: 'Food Court',
    short_name: 'Food Court',
    description: 'Student food court with multiple food stalls, snacks, beverages, and seating area.',
    category: 'food',
    floor_count: 1,
    coordinates: { lat: 30.5158, lng: 76.6622 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: false,
      has_accessible_restroom: false,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['Street food', 'Beverages', 'Quick bites', 'Outdoor seating'],
    operating_hours: {
      monday: { open: '11:00', close: '22:00', is_closed: false },
      tuesday: { open: '11:00', close: '22:00', is_closed: false },
      wednesday: { open: '11:00', close: '22:00', is_closed: false },
      thursday: { open: '11:00', close: '22:00', is_closed: false },
      friday: { open: '11:00', close: '23:00', is_closed: false },
      saturday: { open: '11:00', close: '23:00', is_closed: false },
      sunday: { open: '11:00', close: '21:00', is_closed: false },
    },
    marker_emoji: '🚚',
    marker_color: '#EA580C',
  },
  {
    building_id: 'atm_bank',
    name: 'ATM & Banking',
    short_name: 'ATM',
    description: 'ATM facilities and banking services for students and staff.',
    category: 'services',
    floor_count: 1,
    coordinates: { lat: 30.5148, lng: 76.6600 },
    accessibility: {
      wheelchair_accessible: true,
      has_elevator: false,
      has_ramp: true,
      has_accessible_restroom: false,
      has_braille_signage: false,
      has_audio_guidance: false,
      step_free_entrance: true,
    },
    services: ['ATM (SBI)', 'Bank branch', 'Account services'],
    operating_hours: {
      monday: { open: '09:00', close: '17:00', is_closed: false },
      tuesday: { open: '09:00', close: '17:00', is_closed: false },
      wednesday: { open: '09:00', close: '17:00', is_closed: false },
      thursday: { open: '09:00', close: '17:00', is_closed: false },
      friday: { open: '09:00', close: '17:00', is_closed: false },
      saturday: { open: '09:00', close: '13:00', is_closed: false },
      sunday: { open: '00:00', close: '00:00', is_closed: true },
    },
    marker_emoji: '🏦',
    marker_color: '#166534',
  },
];

export const PATHS = [
  { from: 'main_gate', to: 'admin_block', distance: 100, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'main_gate', to: 'parking_main', distance: 60, walk_time: 1, is_accessible: true, has_stairs: false },
  { from: 'admin_block', to: 'library', distance: 180, walk_time: 3, is_accessible: true, has_stairs: false },
  { from: 'admin_block', to: 'atm_bank', distance: 90, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'library', to: 'cafeteria', distance: 150, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'library', to: 'cs_block', distance: 120, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'cs_block', to: 'engineering_block', distance: 100, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'engineering_block', to: 'innovation_hub', distance: 140, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'cafeteria', to: 'food_court', distance: 110, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'cafeteria', to: 'medical_center', distance: 160, walk_time: 3, is_accessible: true, has_stairs: false },
  { from: 'auditorium', to: 'cs_block', distance: 90, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'auditorium', to: 'sports_complex', distance: 180, walk_time: 3, is_accessible: true, has_stairs: false },
  { from: 'sports_complex', to: 'boys_hostel', distance: 140, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'boys_hostel', to: 'girls_hostel', distance: 130, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'girls_hostel', to: 'innovation_hub', distance: 120, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'library', to: 'engineering_block', distance: 150, walk_time: 3, is_accessible: true, has_stairs: false },
  { from: 'innovation_hub', to: 'food_court', distance: 130, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'admin_block', to: 'auditorium', distance: 200, walk_time: 3, is_accessible: true, has_stairs: false },
  { from: 'parking_main', to: 'admin_block', distance: 120, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'atm_bank', to: 'cafeteria', distance: 100, walk_time: 2, is_accessible: true, has_stairs: false },
  { from: 'cs_block', to: 'boys_hostel', distance: 200, walk_time: 3, is_accessible: true, has_stairs: false },
  { from: 'medical_center', to: 'atm_bank', distance: 90, walk_time: 2, is_accessible: true, has_stairs: false },
];

export const SAMPLE_EVENTS: Event[] = [
  {
    event_id: 'event_001',
    title: 'AI Seminar: Future of Machine Learning',
    description: 'Guest lecture by Dr. Smith on the latest advances in AI and ML technologies.',
    building_id: 'cs_block',
    room: 'Seminar Hall, Ground Floor',
    start_time: new Date(Date.now()).toISOString(),
    end_time: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    event_type: 'seminar',
    affects_navigation: false,
    is_active: true,
  },
  {
    event_id: 'event_002',
    title: 'Library Path Maintenance',
    description: 'Pathway between Admin Block and Library under maintenance. Use alternate route via Cafeteria.',
    building_id: 'library',
    room: 'Outdoor pathway',
    start_time: new Date(Date.now()).toISOString(),
    end_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    event_type: 'maintenance',
    affects_navigation: true,
    blocked_paths: ['admin_block-library'],
    alternate_route_note: 'Use the route via ATM/Bank and Cafeteria (+2 min)',
    is_active: true,
  },
  {
    event_id: 'event_003',
    title: 'Annual Sports Day',
    description: 'Annual sports competition with inter-department events.',
    building_id: 'sports_complex',
    room: 'Main Ground',
    start_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000).toISOString(),
    event_type: 'sports',
    affects_navigation: true,
    alternate_route_note: 'Sports Complex area may be congested. Consider using perimeter paths.',
    is_active: false,
  },
  {
    event_id: 'event_004',
    title: 'Tech Fest Registration',
    description: 'Registration desk for the annual tech fest. Open from 9 AM to 5 PM.',
    building_id: 'auditorium',
    room: 'Lobby',
    start_time: new Date(Date.now()).toISOString(),
    end_time: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    event_type: 'cultural',
    affects_navigation: false,
    is_active: true,
  },
  {
    event_id: 'event_005',
    title: 'End Semester Exam - CS101',
    description: 'Computer Science fundamentals exam for first year students.',
    building_id: 'cs_block',
    room: 'Room 201, 202, 203',
    start_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
    event_type: 'exam',
    affects_navigation: true,
    alternate_route_note: 'De-Morgan Block will have restricted entry during exam hours.',
    is_active: false,
  },
];

export const QUICK_ACTIONS = [
  { label: 'Health Center', query: 'Where is the health center?', emoji: '🏥' },
  { label: 'Nearest Food', query: 'Where can I get food nearby?', emoji: '🍕' },
  { label: 'LRC Hours', query: 'Is the library open now?', emoji: '📚' },
  { label: 'Find Parking', query: 'Where can I park?', emoji: '🅿️' },
  { label: 'Today\'s Events', query: 'What events are happening today?', emoji: '🗓️' },
  { label: 'Accessible Route', query: 'I need an accessible route', emoji: '♿' },
];
